storageService.create_file: raise HTTP errors, refactor
artefactual/archivematica pull request #1049
Opened 2018-04-08 01:22 UTC by hakamine

Fixes #815 
Note that this only fixes the issue of the "store AIP" job/micro-service not failing if getting an error from the SS (probably also need to roll back changes in the SS database in another PR)

2018-04-08 14:12 UTC, sevein commented on src/archivematicaCommon/lib/storageService.py
> +    except (requests.exceptions.RequestException, requests.exceptions.HTTPError) as e:
`requests.RequestException` is the base class in Request library so we're already catching all the subclasses too. See https://github.com/requests/requests/blob/master/requests/exceptions.py.

2018-04-08 14:19 UTC, sevein requested changes
Thanks for doing this, @hakamine.

2018-04-08 14:19 UTC, sevein commented on src/archivematicaCommon/lib/storageService.py
> +    except (requests.exceptions.RequestException, requests.exceptions.HTTPError) as e:
`requests.RequestException` is the base class in Request library so we're already catching all the subclasses too. See https://github.com/requests/requests/blob/master/requests/exceptions.py.

2018-04-08 14:19 UTC, sevein commented on src/archivematicaCommon/lib/storageService.py
> +        response.raise_for_status()
👍

2018-04-08 14:19 UTC, sevein commented on src/archivematicaCommon/lib/storageService.py
>          return (None, e)
FYI I think that at some point we should change the way this function returns - it happens with other functions in this module. We shouldn't be returning the error, the idiomatic way in Python is to return the expected value or raise an exception instead. Pretty much like requests is doing too! An exception can carry information about the error too. To be clear, I'm not asking to change it - just saying! :)

2018-04-09 23:03 UTC, hakamine commented
Thank you @sevein. As suggested, create_file has been refactored to return the expected value or raise an exception instead (also parts of the code that call this function have been fixed accordingly). Did a quick test storing to aipstore and backlog, and it seems working fine.

2018-04-10 15:25 UTC, sevein commented
@hakamine thanks, I've added a couple of fixes: I changed the signature of a return we left behind in the create_file function and an extra commit that it's more of a cosmetic change where we avoid the `else` and its nesting if the `except` is a catch-all.

2018-04-10 23:26 UTC, hakamine commented
Thank you @sevein!  Would it be ok if I squash and merge?

2018-04-17 17:11 UTC, sevein approved these changes

2018-04-17 17:19 UTC, merged