Creates a Dataverse transfer type
artefactual/archivematica pull request #1218
Opened 2018-07-24 19:12 UTC by ross-spencer

This PR introduces a new module `processworkflowjson.py` which allows a workflow inside Archivematica to be defined using a JSON configuration.

The module is used to establish a completely new workflow that runs in parallel to the current Archivematica workflow. 

Initially, as the Dataverse POC is evaluation this workflow remains completely in parallel. Some links may need to be removed, some might need to happen earlier in the process and some might need to be added. 

It is recognised talking to @sevein that using the `variablelinkpull` technique to link the chain together in places will be more appropriate. 

Weaknesses when not using that approach include:

* Not being able to use the processing config to automate decisions such as format identification because they are completely different chain links now. 

Compromises made in this code to get up and running:

* AIP METS 2 still needs to be merged to incorporate Dataverse specific changes instead of forking out to a Dataverse module (this should happen post POC once the Dataverse METS has been analysed). 
* No quarantine links
* No create tree link (in some cases for Dataverse this happens too early in the process because some Dataverse datasets are zipped first)
* No policy check microservices on transfer
* No examine contents microservices on transfer 

A benefit:

* Extract contents is no longer recursive so this is good for zipped Dataverses: https://github.com/artefactual/archivematica/issues/1148

In my mind, to complete this work:

[ ] The new chainling migrations need to be signed-off on. 
[ ] The storage service PR needs review: https://github.com/artefactual/archivematica-storage-service/pull/386
[ ] The storage service needs to be changed to improve AM browsing
[ ] I need to learn how to use variable link pull fields in the database to improve chain linking
[ ] **I will come back to this list and refine it with the help of the team**

2018-07-25 19:38 UTC, ross-spencer commented
Once merged, we can close this too: https://github.com/artefactual/archivematica/pull/347 (Let's verify we have captured everything in the PR)

2018-07-27 17:06 UTC, sevein requested changes

2018-07-27 17:06 UTC, sevein commented on src/dashboard/src/main/processworkflowjson.py
> +# -*- coding: utf-8 -*-
The problem with a helper like this is that it's designed against a specific version of the data model. Perhaps the migrations in this pull request can leverage this work but this module will become obsolete as soon as we introduce backward incompatible in the schema, which we will for sure, we do all the time.

I think this is why we haven't implemented something like this before. Each migration is targeting a specific snapshot of the schema, e.g. migration 0056 was developed with 0055 in mind. If we had your `processworkflowjson` module up to date according to the schema changes then the old migrations would potentially break.

2018-07-27 17:06 UTC, sevein commented on src/dashboard/src/main/processworkflowjson.py
> +# -*- coding: utf-8 -*-
I think this problem to some extend also affects your idea of having JSON documents describing the changes. Who can read these files? `processworkflowjson`? Then we'd have the same problem.

You could have a particular migration being fed from that JSON document(s) but what would be the point then? Can't you just achieve the same with simple Python data structures like lists, sets, dicts, ordered dicts?

Also I suspect that you wouldn't feel the urge for this solution if the set of workflow changes you needed were smaller. Now it's pretty big because you're wanting to have a whole different workflow. My recommendation would be to step back, identify the minimal set of changes and implement those. Potentially your migration would look much simpler, e.g. see `0041_bind_pids.py`.

2018-07-27 17:06 UTC, sevein commented on src/dashboard/src/components/filesystem_ajax/views.py
> +    'dataverse': 'dataverseTransfer'
Now in qa/1.x you also have to make similar update in `package.py`.

2018-07-27 17:06 UTC, sevein commented on src/dashboard/src/main/migrations/0052_dataverse_foreign_keys.py
> +from __future__ import unicode_literals
Something to remember: migrations are very slow! A changeset like the one in this PR should only bring one migration so it's important to jointhem before merging.

2018-07-27 17:06 UTC, sevein commented on src/MCPClient/lib/clientScripts/parse_dataverse.py
> +    parser.add_argument('transfer_dir', action='store', type=str, help="%SIPDirectory%")
FYI: `store` is the default action, `str` is the default type.

2018-08-21 02:24 UTC, ross-spencer commented
Closing as this will be superseded by the work here: https://github.com/artefactual/archivematica/tree/dev/issue-1147-minimal-dataverse-transfer-type

2018-08-21 02:24 UTC, closed without merging

2018-08-21 16:17 UTC, ross-spencer commented
Replaced by: https://github.com/artefactual/archivematica/pull/1242