Upgrade ES support to version 6.x
artefactual/archivematica pull request #1285
Opened 2018-10-05 17:16 UTC by jraddaoui

WIP.

Connects to #1171.

2018-10-09 15:07 UTC, jraddaoui commented
Hi @sevein (@ross-spencer and @jhsimpson your thoughts are welcome too),

This is ready for a first review. I tried to not change a lot the current implementation in this first round and just focus on upgrading the version support, but I've added some TODOs? in the description for things that could be improved further, and I guess you'll have a few more. We may not have time to do them all, so I'd like to hear you thoughts about them and the changes to this point before moving forward.

Thanks!

2018-11-22 18:24 UTC, sevein reviewed
Looking good, @jraddaoui. I hope the tests can be updated easily!

Your TODO lists some good ideas. Hopefully we can address those separately, we can probably find good ways to group them where it makes sense.

2018-11-22 18:24 UTC, sevein commented on src/dashboard.Dockerfile
> +		unar \
The same dependency needs to be added to Dashboard's osdeps files.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> -    return results['_indices'][index]['_shards']['successful'] == results['_indices'][index]['_shards']['total']
What are the implications of not returning? e.g. `delete_aip_files` is still returning the returned value.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +INDICES = ['aips', 'aipfiles', 'transfers', 'transferfiles']
Nitpick: indices or indexes? Both are valid I think but we're using both, it'd be nice if we just use one of the forms across the board for consistency.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +    Checks if all indeces exist in the client. Otherwise, creates the missing
Typo: `s/indeces/indices`.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +INDICES = ['aips', 'aipfiles', 'transfers', 'transferfiles']
You could add a comment here describing how the code expects funcs like `_get_aips_index_body` to be defined. It'd be nice for the developer to know what it takes to add a new index.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +    """
Note that in AM docstrings are written following a different format. See https://www.python.org/dev/peps/pep-0257/#id17:

> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description. The summary line may be used by automatic indexing tools; it is important that it fits on one line and is separated from the rest of the docstring by a blank line. The summary line may be on the same line as the opening quotes or on the next line. The entire docstring is indented the same as the quotes at its first line (see example below).

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +        # Call get index body functions bellow for each index
Typo: below.

2018-11-22 18:24 UTC, sevein commented on src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py
> +        """Delete search indeesx."""
Typo.

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +DOC_TYPE = '_doc'
Makes sense!

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +        logger.info('Creating "%s" index ...' % index)
String replacement in `logging` is usually done as follows:

    logger.info('Creating "%s" index ...', index)

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +        if aip_type == 'Archival Information Collection':
JD used to prefer double quoting. I think we need to write down our style preference project-wise so we don't keep making the same kind of change.

2018-11-22 18:24 UTC, sevein commented on src/dashboard/src/components/advanced_search.py
> +            # FIXME
?

2018-11-22 18:24 UTC, sevein commented on src/dashboard/src/components/archival_storage/views.py
> +    # FIXME
No facets, is that the problem?

2018-11-22 18:24 UTC, sevein commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +    )
Nice!

2018-11-22 18:24 UTC, sevein commented on src/dashboard/src/components/backlog/views.py
> +        hit_count = hits['hits']['total']
Nice!

2018-11-22 18:24 UTC, sevein commented
I've rebased!

2018-12-28 17:33 UTC, jraddaoui commented on src/dashboard/src/components/advanced_search.py
> +            # FIXME
Mapping changes for this version required some fixes in this code. In the end with ES 6.x there was no need to get the sub-fields, check https://github.com/artefactual/archivematica/pull/1285/commits/7018be000089c95911b1888bdf02abc8424f0cbd.

2018-12-28 17:35 UTC, jraddaoui commented on src/dashboard/src/components/archival_storage/views.py
> +    # FIXME
Yes, it was fixed in https://github.com/artefactual/archivematica/pull/1285/commits/f7ba54379a2132d3063304b58400554446c846b5.

2018-12-28 17:37 UTC, jraddaoui commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +        if aip_type == 'Archival Information Collection':
OK, sorry. I'll try to change quotes as less as possible until we have the style defined.

2018-12-28 17:52 UTC, jraddaoui commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> -    return results['_indices'][index]['_shards']['successful'] == results['_indices'][index]['_shards']['total']
The returned value is not checked in any of the delete calls. I have removed some of those not needed returns in https://github.com/artefactual/archivematica/pull/1285/commits/1129d8f068dfa355527a2f827eeba80212af0c25.

2018-12-28 17:53 UTC, jraddaoui commented on src/dashboard.Dockerfile
> +		unar \
Done.

2018-12-28 18:07 UTC, jraddaoui commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +INDICES = ['aips', 'aipfiles', 'transfers', 'transferfiles']
Done.

2018-12-28 18:23 UTC, jraddaoui commented on src/archivematicaCommon/lib/elasticSearchFunctions.py
> +    """
Thanks! I have fixed a few more in https://github.com/artefactual/archivematica/pull/1285/commits/28a56030181f6edd3646de0c6433b76ce81dd018.

2019-01-03 17:15 UTC, jraddaoui commented
Hi @sevein, this is ready for another round! Sorry for the delay.

2019-01-03 17:22 UTC, jraddaoui commented
I have created https://github.com/archivematica/Issues/issues/404 for the other improvements from the description.

2019-01-03 23:02 UTC, sevein approved these changes
Thanks, @jraddaoui! Once this is merged, have you thought about next action items? I can imagine this is going to require some work in other repos, e.g.:

- https://github.com/artefactual-labs/ansible-archivematica-src (are we going to need a new branch?)
- https://github.com/artefactual/archivematica-docs (branch 1.9?)
- https://github.com/artefactual/deploy-pub (playbooks)

2019-01-03 23:02 UTC, sevein commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +    from mock import ANY, patch
I've been just using `from mock import ANY, patch` assuming that it becomes no-op in Python3 but I guess you way is more explicit.

2019-01-04 16:33 UTC, jraddaoui commented
Good point @sevein, I've sent an email to the team to check a few things before merging ;)

2019-01-21 13:15 UTC, mamedin requested changes

2019-01-21 13:15 UTC, mamedin commented on src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py
> +                # "size": options["size"],
Hi Radda,

I tested a migration from ES version 1.7.6 to version 6.5.4. The aips index has 24805 documents, and the data directory is 177M. I found this error when running the new `reindex_from_remote_cluster` command:

```
archivematica@mamedin-elasticcsearch-test:/usr/share/archivematica/dashboard$ /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py reindex_from_remote_cluster http://127.0.0.1:9600
Reindexing aips:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/archivematica/archivematica/src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py", line 147, in handle
    body=body,
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 783, in reindex
    params=params, body=body)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/share/archivematica/virtualenvs/archivematica-dashboard/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, u'illegal_argument_exception', u'Remote responded with a chunk that was too large. Use a smaller batch size.')
```
I tested with several batch sizes, for example 50 and 10. It works for size=10:

```
root@mamedin-elasticcsearch-test:/opt/archivematica/archivematica/src/dashboard# git diff src/main/management/commands/reindex_from_remote_cluster.py
diff --git a/src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py b/src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py
index 2184cd97..12a1b024 100644
--- a/src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py
+++ b/src/dashboard/src/main/management/commands/reindex_from_remote_cluster.py
@@ -99,6 +99,7 @@ class Command(DashboardCommand):
                 },
                 "index": "",
                 "type": "",
+                "size": "10"
                 # "size": options["size"],
             },
             "dest": {
```

It took 47s to reindex, this is the output including the `time`command:

```artefactual@mamedin-elasticcsearch-test:~/elasticsearch-1.7.6/elasticsearch-1.7.6$ sudo su - archivematica -s /bin/bash
archivematica@mamedin-elasticcsearch-test:~$ export $(cat /etc/default/archivematica-dashboard)
-su: export: `#': not a valid identifier
archivematica@mamedin-elasticcsearch-test:~$ cd /usr/share/archivematica/dashboard
archivematica@mamedin-elasticcsearch-test:/usr/share/archivematica/dashboard$ ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT=300 time /usr/share/archivematica/virtualenvs/archivematica-dashboard/bin/python manage.py reindex_from_remote_cluster http://127.0.0.1:9600
Reindexing aips:
{
    "retries": {
        "bulk": 0, 
        "search": 0
    }, 
    "updated": 0, 
    "batches": 3, 
    "throttled_until_millis": 0, 
    "throttled_millis": 0, 
    "noops": 0, 
    "created": 115, 
    "deleted": 0, 
    "took": 15592, 
    "requests_per_second": -1.0, 
    "timed_out": false, 
    "failures": [], 
    "version_conflicts": 0, 
    "total": 115
}
Reindexing aipfiles:
{
    "retries": {
        "bulk": 0, 
        "search": 0
    }, 
    "updated": 0, 
    "batches": 506, 
    "throttled_until_millis": 0, 
    "throttled_millis": 0, 
    "noops": 0, 
    "created": 24690, 
    "deleted": 0, 
    "took": 30185, 
    "requests_per_second": -1.0, 
    "timed_out": false, 
    "failures": [], 
    "version_conflicts": 0, 
    "total": 24690
}
Reindexing transfers:
{
    "retries": {
        "bulk": 0, 
        "search": 0
    }, 
    "updated": 0, 
    "batches": 0, 
    "throttled_until_millis": 0, 
    "throttled_millis": 0, 
    "noops": 0, 
    "created": 0, 
    "deleted": 0, 
    "took": 11, 
    "requests_per_second": -1.0, 
    "timed_out": false, 
    "failures": [], 
    "version_conflicts": 0, 
    "total": 0
}
Reindexing transferfiles:
{
    "retries": {
        "bulk": 0, 
        "search": 0
    }, 
    "updated": 0, 
    "batches": 0, 
    "throttled_until_millis": 0, 
    "throttled_millis": 0, 
    "noops": 0, 
    "created": 0, 
    "deleted": 0, 
    "took": 10, 
    "requests_per_second": -1.0, 
    "timed_out": false, 
    "failures": [], 
    "version_conflicts": 0, 
    "total": 0
}
0.60user 0.10system 0:47.25elapsed 1%CPU (0avgtext+0avgdata 57308maxresident)k
4440inputs+48outputs (0major+24062minor)pagefaults 0swaps
```

2019-01-21 17:50 UTC, jraddaoui commented
Hi @sevein,

I have squashed all the work already reviewed and added a new commit which includes a command to re-index the documents from a remote cluster. I'd appreciate if you could review that commit ;)

@mamedin, I have added a couple of optional arguments to the command to allow setting the chunk size and the request timeout. I'll follow-up about that in the Redmine ticket and related email thread.

2019-01-21 18:10 UTC, mamedin approved these changes
I tested again with the new options for batch size and timeout and it works fine.

2019-01-22 13:09 UTC, jraddaoui commented
Hi @sevein,

I have simplified the command a bit as I was adding options to keep and merge the indexes that in the end I think we should remove, to avoid confusions and ease the documentation. Also, the `--timeout` (`-t`) param will now be used for both connections to avoid changing the config/env only for the execution of this command.

2019-01-22 14:23 UTC, sevein approved these changes
@jraddaoui the command looks fine, thanks! I haven't tested but no red flags. One thought is that you subclass `DashboardCommand` but you're not really taking advantage of its methods. You certainly could. In particular I wonder if we should control exceptions raised by `reindex` so we can print friendlier messages.

:+1:

2019-01-23 12:13 UTC, jraddaoui commented
> @jraddaoui the command looks fine, thanks! I haven't tested but no red flags. One thought is that you subclass `DashboardCommand` but you're not really taking advantage of its methods. You certainly could. In particular I wonder if we should control exceptions raised by `reindex` so we can print friendlier messages.

Thanks @sevein! I've improved a little the output of the command. Please, let me know if that's okay before I merge.

2019-01-23 15:23 UTC, sevein approved these changes
Cool, thanks! :+1:

2019-01-23 18:30 UTC, merged