Fix minor issues with the Dataverse transfer type
artefactual/archivematica pull request #1290
Opened 2018-10-11 22:37 UTC by ross-spencer

:construction: :construction: :construction:

2018-10-16 22:52 UTC, sevein commented on src/dashboard/src/main/migrations/0061_create_dataverse_transfer_type.py
> +
Can't comment above but there's a small typo:
`EXISTING_MS_VAILIDATE_FORMATS`

2018-12-17 23:39 UTC, sevein reviewed
@ross-spencer does this need to be rebased?

2018-12-21 01:13 UTC, sevein requested changes
Needs to be rebased.

2019-01-17 00:07 UTC, ross-spencer commented
Closed in favor of https://github.com/artefactual/archivematica/pull/1332

2019-01-17 00:07 UTC, closed without merging