Return Exceptions in JSON response
artefactual/archivematica pull request #1310
Opened 2018-12-01 22:31 UTC by helrond

See archivematica/Issues#354

2018-12-09 17:04 UTC, sevein requested changes
@helrond thanks for doing this! I've only added a tiny observation.

Thanks for improving this area of the application, it's definitely very improvable! Slightly unrelated, but I find somewhat cumbersome that `start_transfer` is dealing with concerns like returning API objects or logging. Even its location in `filesystem_ajax.views` is questionable. It could use a facelift for sure.

2018-12-09 17:04 UTC, sevein commented on src/dashboard/src/components/filesystem_ajax/views.py
> +            raise Exception('Error starting transfer: {}'.format(filepath, e))
The string is not using the second argument `e`, can you remove it?

2018-12-09 23:28 UTC, helrond commented
Thanks @sevein! I changed the exception and the logging error so they're both the same, and also both return the actual exception thrown. 

I agree with your observation about `filesystem_ajax.views` - a lot of what's in that file doesn't, IMO, have anything to to with views. Making sure the Archivematica API works is high on my list of priorities, so I'd be interested in looking at this some more if that aligns with the roadmap and other ideas about the API.

2018-12-18 14:49 UTC, sevein approved these changes

2018-12-18 19:11 UTC, merged