Validation API
artefactual/archivematica pull request #1400
Opened 2019-04-04 15:20 UTC by sevein

No issue atm, only [ADR-0005](https://adr.archivematica.org/0005-new-api-endpoint-for-csv-validation.html).

2019-04-04 20:26 UTC, cole requested changes
Nice, this looks pretty good!

The main thing I see here I'm still confused by what we are achieving with base64 encoding — it seems like an unnecessary extra step. Do we need to support other encodings than UTF-8? I would highly recommend only supporting UTF-8, in which case I think it makes sense to fail early if the encoding is invalid.

There's also a few minor things inline.

2019-04-04 20:26 UTC, cole commented on src/dashboard/src/components/api/validators.py
> +class ValidatorNotAvailableError(Exception):
It may make more sense to subclass [ValueError]( https://docs.python.org/2/library/exceptions.html#exceptions.ValueError) here.

2019-04-04 20:26 UTC, cole commented on src/dashboard/src/components/api/views.py
> +    except Exception:
`    except ValueError:`

2019-04-04 20:26 UTC, cole commented on src/dashboard/src/components/api/views.py
> +        return _ok_response({"valid": False, "reason": six.text_type(err)})
This should be HTTP 400 response.

2019-04-04 22:42 UTC, ablwr commented
I think the base64 encoding provides value. People come up with the weirdest, most unexpected things...

2019-04-05 14:52 UTC, sevein commented
Thanks @cole and @ablwr for the feedback. I've updated my changes so the document can be embedded in the body of the request. See the updated description of the pull request for usage examples.

Now the encoding and mime type can be determined using the `Content-Type` header - for now I'm just expecting `"text/csv; charset=utf-8"` but that should give us some flexibility in the future.

2019-04-05 16:43 UTC, cole commented on src/dashboard/src/components/api/views.py
> +        return _ok_response({"valid": False, "reason": six.text_type(err)})
I should clarify this comment a bit for posterity — there is a case to be made either way, like all REST API status codes, it's a bit of a judgement call. You can make the argument that validation succeeded and the result was failure, but I think an error status code is more useful for clients if validation failed.

2019-04-05 16:44 UTC, cole approved these changes
Nice, I like this solution. Looks good!

2019-04-10 17:59 UTC, ablwr approved these changes

2019-04-10 18:00 UTC, ablwr commented
Tagging @helrond in case Hillel is curious as to the implementation of this. Could you see this being extended for a rights.csv or metadata.csv?

2019-04-10 18:44 UTC, helrond commented
@ablwr Yes, this looks _exactly_ like what I had in mind for validating those other CSV files! Am I right in thinking that there isn't validation logic elsewhere in the application that could be leveraged for rights.csv and/or metadata.csv, so this would have to be extended with additional validators?

2019-04-10 18:45 UTC, ablwr commented
@helrond Yeah, that's right. The only validation logic right now is for Avalon Media System. I hope we can add other validators in the future, though! I spend a lot of time helping people puzzle over metadata.csv.

2019-04-10 18:48 UTC, helrond commented
@ablwr This looks like it will be super easy to extend, and this might actually be a place where we could jump in with a PR if that's desirable. Thanks for bringing it to my attention!

2019-04-12 16:32 UTC, ablwr requested changes
Getting incorrect results here when testing -- investigating and will follow up with more feedback.

2019-04-12 17:54 UTC, sevein commented
> Getting incorrect results here when testing -- investigating and will follow up with more feedback.

Ok @ablwr thanks for testing. I'm curious to hear more.

Here's the command that I've been using to just run the tests under the new TestValidate class:

    docker-compose exec archivematica-dashboard bash -c "cd /src/dashboard && py.test -p no:cacheprovider --reuse-db -x -v -k TestValidate"

2019-04-12 18:11 UTC, ablwr commented
I am getting `{"valid": true}` whenever I pass in a CSV that is not valid.

If I pass in something that doesn't exist, I get the expected error. 

It's funny, I am getting inconsistent results and trying to replicate them, because previously I was receiving an error, but of the wrong type, and for everything I passed into it. It is almost as if the API is getting stuck in some sort of way -- could it always be testing on the first file passed in instead of new data? I don't know exactly what is wrong, but CSVs that should fail are just returning as valid:true.

2019-04-12 20:07 UTC, ablwr commented
OK, the issue was cURL not being happy with linebreaks, and @sevein changing the example from `--data` to `--data-binary` sorted it all out! I also tested out this most recent update, in which @sevein checks that a file has at least three rows. :tada:

2019-04-12 20:07 UTC, ablwr approved these changes

2019-05-24 21:31 UTC, merged