WIP: Revert "ESfunctions: replace ElementTree with lxml.etree"
artefactual/archivematica pull request #1408
Opened 2019-04-17 22:05 UTC by hakamine

This reverts commit 7c5da722c761d42371ff7ae4b583071a9c2f6b6f.

2019-04-27 12:58 UTC, jraddaoui requested changes
Thanks for the quick turnaround @hakamine, this is looking really great!

I've added some minor comments bellow, mostly cosmetic. My biggest concerns are to reflect why the `Elementpath._cacche_clear()` calls are needed and to reduce the METS files added for the test. For the later, maybe we could reuse some existing METS files or simplify the ones included in here, just having one file on each one with the less data required to be a a valid METS file.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/lib/namespaces.py
> +        ElementPath._cache.clear()
I'd appreciate a note explaining why is this needed. Maybe at the module level, as it's done in almost all the functions.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +# to be able to use @pytest.mark.parametrize
I'd remove this comment.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +    # obtained from the METS
A docstring will probably look better in here.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +    identifiers = []
This four variables are only used in the function call bellow so you could avoid their declaration.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +    # check number of indexed files is correct
Uppercase first for consistency.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +        assert indexed_fileuuid == file_uuid["FILEUUID"]
No need to declare `ìndexed_fileuuid` in here, it could all go in one line.

2019-04-27 12:58 UTC, jraddaoui commented on src/archivematicaCommon/tests/test_elasticsearch_functions.py
> +    assert dummy_try_to_index.call_count == filecount
Are this checks needed for this test? I think we should only check the file UUID parsing to reduce the METS files.

2019-04-29 17:53 UTC, hakamine commented
HI @jraddaoui  , thank you very much for the code review. I think I addressed all comments, hopefully this is good to merge now.

2019-04-29 17:59 UTC, jraddaoui approved these changes
Thanks a lot @hakamine!

Please, for the next time, try to add the feedback changes in extra commits to make it easier for the reviewer, we can always merge with `--squash` after ;)

2019-04-29 19:55 UTC, merged