Support gzip compression of AIP
artefactual/archivematica pull request #1412
Opened 2019-05-08 14:24 UTC by helenst

2019-05-28 13:06 UTC, ross-spencer approved these changes
Works and LGTM! :+1:

2019-05-28 13:10 UTC, ross-spencer commented
Oh, sorry @helenst I might have approved that a bit quickly. I am just getting feedback on `gzip` as a label in the UI - if that needs a change I'll ask you to do that and then I'll get this branch merged.

2019-05-29 17:31 UTC, ross-spencer requested changes
Following up with one change, and possibly a corresponding change for the `TRANSFORMALGORITHM` field in the pointer file if required here vs. in the Storage Service. Once that's done, We'll get you to rebase the commits and I can continue with the merge. 

I am tempted to wait until after this is fixed for `1.10` in case there are any corresponding changes required here or in the Storage Service: https://github.com/archivematica/Issues/issues/713

2019-05-29 17:31 UTC, ross-spencer commented on src/MCPServer/lib/assets/workflow.json
> +                        }
We chatted at AMHQ and if possible we'd like to see this changed to `Gzipped tar`. Would you be able to alphabetize the output too? I think this will do it, syntax just needs double checking:
```json
                "replacements": [
                    {
                        "description": {
                            "en": "7z using bzip2",
                            "es": "7z usando bzip2",
                            "fr": "7z utilisant bzip2",
                            "ja": "7z（bzip2を利用）",
                            "pt_BR": "7z usando bzip2",
                            "sv": "7z användande bzip2"
                        },
                        "id": "9475447c-9889-430c-9477-6287a9574c5b",
                        "items": {
                            "AIPCompressionAlgorithm": "7z-bzip2"
                        }
                    },
                    {
                        "description": {
                            "en": "7z using lzma",
                            "es": "7z usando lzma",
                            "fr": "7z utilisant lzma",
                            "ja": "7z（lzmaを利用）",
                            "pt_BR": "7z usando lzma",
                            "sv": "7z using Izma"
                        },
                        "id": "c96353b9-0d55-46cf-baa0-d7c3e180dd43",
                        "items": {
                            "AIPCompressionAlgorithm": "7z-lzma"
                        }
                    },
                    {
                        "description": {
                            "en": "7z without compression (Copy)",
                            "pt_BR": "7z sem compressão (Cópia)"
                        },
                        "id": "e3906da0-41fb-4cb8-a598-6c73981b63e9",
                        "items": {
                            "AIPCompressionAlgorithm": "7z-copy"
                        }
                    },
                    {
                        "description": {
                            "en": "Gzipped tar"
                        },
                        "id": "9ce711ab-96d1-45dd-8708-de69698c1424",
                        "items": {
                            "AIPCompressionAlgorithm": "gzip-"
                        }
                    },
                    {
                        "description": {
                            "en": "Parallel bzip2",
                            "es": "bzip2 paralelo",
                            "pt_BR": "Bzip2 paralelo",
                            "sv": "Parallell bzip2"
                        },
                        "id": "f61b00a1-ef2e-4dc4-9391-111c6f42b9a7",
                        "items": {
                            "AIPCompressionAlgorithm": "pbzip2-"
                        }
                    },
                    {
                        "description": {
                            "en": "Uncompressed",
                            "pt_BR": "Sem comprimir",
                            "sv": "Okomprimerat"
                        },
                        "id": "dc04c4c0-07ea-4796-b643-66d967ed33a4",
                        "items": {
                            "AIPCompressionAlgorithm": "None-"
                        }
                    }                
                ]
            },
```

2019-06-04 13:17 UTC, helenst commented on src/MCPServer/lib/assets/workflow.json
> +                        }
Done :)

2019-06-04 14:01 UTC, ross-spencer approved these changes
:+1: LGTM!

2019-06-04 14:03 UTC, merged