Add support for transferring non-bagged zipfiles
artefactual/archivematica pull request #1413
Opened 2019-05-08 14:42 UTC by helenst

Add an option to the transfer type dropdown allowing a plain zipfile to be selected.

The MCPClient script for extracting bagged zips has been adapted and renamed so that it is used for both bagged and unbagged zips, since the code is so similar. A flag is provided to distinguish whether the file is expected to be a bag.

Fixes https://github.com/archivematica/Issues/issues/682

2019-12-19 20:15 UTC, sromkey commented
Hey @artefactual/amcr group, I think this is ready for CR based on discussion with Helen on the issue.

2020-02-09 11:46 UTC, ross-spencer requested changes
Hi @alexwlchan I have reviewed this and it looks good. Please review the CR notes and let us know the capacity you have to address the rebase this week. While Helen and I were coordinating other PRs, we lost track of the need to rebase this one following changes we made to preserve process configuration in zipped transfers/ You'll see in my notes I submitted what I think is a merged version of [`extract_zipped_transfer.py`](https://github.com/artefactual/archivematica/pull/1556/commits/8ad107d5e6c2c41644e4825a1023bc7dfb8da33f). That needs checking alongside what you're running, and perhaps testing alongside what you desire to be running. Once that's merged, the rebase to `qa/1.x` looks straightforward.

This was a fascinating one to review. I learned a little more about the capability of zip-like transfers and found two `qa/1.x` regressions **nb.** not caused by this PR.

You'll see in the primary body of the PR submitted by Helen I have suggested some docs [here](https://github.com/artefactual/archivematica/pull/1556). It's a very light treatment. Please feel free to review also.

2020-02-09 11:46 UTC, ross-spencer commented on src/MCPClient/lib/clientScripts/extract_zipped_transfer.py
> +                    pass
This code has moved significantly thanks to Helen's work. The work done here for tar files is now done outside of this function. I have created a reference rebase [here](https://github.com/artefactual/archivematica/blob/dev/issue-682-support-zipped-transfers/src/MCPClient/lib/clientScripts/extract_zipped_transfer.py). My suggestion is to review that copy, compare it with the one currently being run at Wellcome, and then submit it back against this PR. As far as I can see it wouldn't require any code changes once rebased. Other  suggestions welcome.

2020-02-09 11:46 UTC, ross-spencer commented on src/MCPServer/lib/assets/workflow.json
> +                "sv": "Godkänn överföring"
Just noting, these changes all look sensible. The new transfer type follows a couple of setup processes before eventually following the standard transfer path. 

**Transfer starts and is approved**

![image](https://user-images.githubusercontent.com/1880412/74094440-4e343d00-4aaf-11ea-8127-4dec5a992bef.png)

**Transfer is extracted**

![image](https://user-images.githubusercontent.com/1880412/74094427-20e78f00-4aaf-11ea-9bb8-b04dc2a10f46.png)

**Transfer follows the standard path**

![image](https://user-images.githubusercontent.com/1880412/74094429-31980500-4aaf-11ea-92a7-b8bbaf2dd12e.png)

2020-02-09 11:46 UTC, ross-spencer commented on src/MCPServer/lib/assets/workflow.json
> +            "path": "/activeTransfers/zippedDirectory",
This directory is created as anticipated:
```
activeTransfers# tree
.
├── baggitDirectory
├── baggitZippedDirectory
├── dataverseTransfer
├── Dspace
├── maildir
├── standardTransfer
├── TRIM
└── zippedDirectory
```

2020-02-09 11:46 UTC, ross-spencer commented on src/dashboard/frontend/app/services/transfer_browser_transfer.service.js
> +    } else if (this.type == 'zipfile') {
It looks like this should be the `===` strict comparison as well?

2020-02-09 12:33 UTC, alexwlchan commented
@ross-spencer I think I’ve addressed the review markups, fancy another look?

2020-02-09 12:38 UTC, alexwlchan commented
why travis 😭 

(investigating)

2020-02-09 13:11 UTC, ross-spencer requested changes
Thanks for the quick response @alexwlchan just two changes that I can see, it looks like they were highlighted by the linter too. I think those changes should make the build happy. If you wanted to give rebasing to apply these changes on top of Artefactual's `qa/1.x` as well to be extra sure about the build, that might be a good idea, but I think when we squish that all will be taken care off anyway.

2020-02-09 13:11 UTC, ross-spencer commented on src/MCPClient/lib/clientScripts/extract_zipped_transfer.py
> +                destinationDirectory = get_extract_dir_name(destinationDirectory)
Looking good, we just need to make sure `get_extract_dir_name(..)` is imported at the top of the file:

* `from fileOperations import get_extract_dir_name`

2020-02-09 13:11 UTC, ross-spencer commented on src/MCPClient/lib/clientScripts/extract_zipped_transfer.py
> -                )
The build tells me 101 to 103 need to be reinstated :)

2020-02-09 13:18 UTC, alexwlchan commented
🤦‍♀ 

Pushed a fixed commit.

2020-02-09 21:05 UTC, ross-spencer commented
Perfect, thank you @helenst and @alexwlchan for this! Will get this merged and so it should appear in `1.11` soon!! 

![image](https://media2.giphy.com/media/L19Fn7nZWfqnmAjTcH/giphy.gif?cid=790b76115f664bc4d45a9307e856aac71ffd6be8ffacafff&rid=giphy.gif)

2020-02-09 21:06 UTC, ross-spencer approved these changes
Perfect, thank you @helenst and @alexwlchan for this! Will get this merged and so it should appear in `1.11` soon!! 

![image](https://media2.giphy.com/media/L19Fn7nZWfqnmAjTcH/giphy.gif?cid=790b76115f664bc4d45a9307e856aac71ffd6be8ffacafff&rid=giphy.gif)

2020-02-09 21:08 UTC, merged