Ensure that we write event id for name cleanup
artefactual/archivematica pull request #1479
Opened 2019-08-30 16:21 UTC by ross-spencer

An event identifier wasn't being written for name cleanup. Now it is.

Tests have been added to look specifically at this, plus a few other
easier to check details that should also be output in an event.

2019-08-30 17:02 UTC, sevein requested changes
Thanks for doing this! I've suggested some changes.

2019-08-30 17:02 UTC, sevein commented on src/MCPClient/lib/clientScripts/sanitize_object_names.py
> +                event_id=uuid.uuid4(),
Could this be moved up so it reads as the first keyword since it's listed first in the model?

2019-08-30 17:02 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +
Could this be a single line like in the other example below?

2019-08-30 17:02 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +            assert event_detail in event[0].event_detail, "Event detail written incorrectly"
I think that I prefer conciseness - it's always preferably to have tests that are easier to scan quickly.

An alternative that I find much more readable and in the spirit of how this test module was originally written:

```python
            event = Event.objects.get(
                file_uuid="47813453-6872-442b-9d65-6515be3c5aa1",
                event_type="name cleanup",
            )

            assert is_uuid(event[0].event_id)
            assert event_detail in event[0].event_detail, "Event detail written incorrectly"
```

Notice that `is_uuid` needs to be implemented which makes sense since you're doing this twice.

I don't think that what I wrote is cryptic, it's still pretty manageable for the average Python/Django dev.

2019-08-30 17:02 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +        assert event_detail in event[0].event_detail, "Event detail written incorrectly"
Same here!

2019-08-30 17:24 UTC, ross-spencer commented on src/MCPClient/tests/test_sanitize.py
> +
This is `black`. I think the previous example was while black was failing.

2019-08-30 17:24 UTC, ross-spencer commented on src/MCPClient/tests/test_sanitize.py
> +            assert event_detail in event[0].event_detail, "Event detail written incorrectly"
Done.

2019-08-30 17:24 UTC, ross-spencer commented on src/MCPClient/tests/test_sanitize.py
> +        assert event_detail in event[0].event_detail, "Event detail written incorrectly"
As above.

2019-08-30 19:44 UTC, ross-spencer commented on src/MCPClient/tests/test_sanitize.py
> +            assert event_detail in event[0].event_detail, "Event detail written incorrectly"
The original suggestion is good, but it is still ambiguous and won't work in its own right. To work it needs to become:
```python
 event = Event.objects.get(
                file_uuid="47813453-6872-442b-9d65-6515be3c5aa1",
                event_type="name cleanup",
            )

            assert is_uuid(event.event_id)
            assert event_detail in event.event_detail, "Event detail written incorrectly"
```
We no longer need to use indexing on the returned object.

The change has been made now too.

2019-08-30 21:56 UTC, sevein requested changes

2019-08-30 21:56 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +        assert event is not None, "Event not returned from database"
This assertion is always going to succeed because `get` raises when the object does not exist.

2019-08-30 21:56 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +        assert event.event_id is not None, "Event ID is None"
We don't need this line, `uuid.UUID(None, version=4)` raises a `TypeError`.

2019-08-30 21:56 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +            assert event is not None, "Event not returned from database"
Above you're doing:

```
event = Event.objects.filter(
    file_uuid="47813453-6872-442b-9d65-6515be3c5aa1",
    event_type="name cleanup",
)
```

I think that it's preferably to use `get` in L219.
The assertion in L225 becomes unnecessary.

2019-08-30 21:56 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +            assert event[0].event_id is not None, "Event ID is None"
We don't need this line, `uuid.UUID(None, version=4)` raises a TypeError.

2019-08-30 21:59 UTC, sevein commented on src/MCPClient/tests/test_sanitize.py
> +        return False
Please align the happy path to the left edge.

```
try:
    uuid.UUID(uuid_, version=4)
except ValueError:
    return False
return True
```

2019-08-31 17:35 UTC, sevein approved these changes
Hey sorry @ross-spencer I noted a few nitpicks yesterday but I'm ok if you choose to merge.

2019-09-18 16:43 UTC, sevein approved these changes

2019-12-13 02:49 UTC, merged