Dev/issue 810 dashboard py3 upgrade rebase
artefactual/archivematica pull request #1575
Opened 2020-02-17 23:41 UTC by ross-spencer

QA branch  for the Dashboard Py3 migration... 

Connected to archivematica/issues#810

2020-02-18 16:07 UTC, ross-spencer commented on src/archivematicaCommon/lib/archivematicaFunctions.py
> +    return base64.b64decode(data.encode("utf8")).decode("utf8")
NB. new helper functions to help across the Dashboard.

2020-02-18 22:07 UTC, ross-spencer commented on src/dashboard/src/components/administration/forms.py
> +            f.write(etree.tostring(self.xml, pretty_print=True, encoding="unicode"))
NB. Because we're serializing to disk I think this needs to be a byte encoding `UTF-8` per https://lxml.de/parsing.html

2020-02-21 13:18 UTC, ross-spencer commented on src/dashboard/src/main/management/commands/__init__.py
> +    result = eval(input("%s " % question))
NB. Check what we did in storage service here, this might not work...

2020-02-25 04:27 UTC, replaceafill reviewed
This looks good to me overall. I left a few comments with minor (potential) cleanups and have two questions:

1. Do you think we should follow the same approach when we merged the Python 3 changes for the Storage Service and address (some of) the warnings produced by `pylint`?

```bash
$ venv3/bin/pylint --py3k $(find * | grep py$)
************* Module src.components.transfer.views
src/components/transfer/views.py:210:15: W1645: Exception.message removed in Python 3 (exception-message-attribute)
src/components/transfer/views.py:215:22: W1645: Exception.message removed in Python 3 (exception-message-attribute)
src/components/transfer/views.py:239:30: W1645: Exception.message removed in Python 3 (exception-message-attribute)
************* Module src.components.administration.views
src/components/administration/views.py:216:55: W1655: dict.keys referenced when not iterating (dict-keys-not-iterating)
************* Module src.components.administration.tests.test_storage
src/components/administration/tests/test_storage.py:1:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.components.administration.tests.test_usage
src/components/administration/tests/test_usage.py:1:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.components.accounts.apps
src/components/accounts/apps.py:1:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.components.accounts.signals
src/components/accounts/signals.py:1:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.components.archival_storage.tests.test_archival_storage
src/components/archival_storage/tests/test_archival_storage.py:22:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.fpr.migrations.0031_update_normalization_rules
src/fpr/migrations/0031_update_normalization_rules.py:7:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.fpr.migrations.0032_pronom_96
src/fpr/migrations/0032_pronom_96.py:4:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module src.fpr.migrations.0033_update_idtools
src/fpr/migrations/0033_update_idtools.py:5:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module test_helpers
tests/test_helpers.py:5:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module test_middleware
tests/test_middleware.py:1:0: W1618: import missing `from __future__ import absolute_import` (no-absolute-import)
************* Module test_filesystem_ajax
tests/test_filesystem_ajax.py:266:42: W1646: non-text encoding used in str.decode (invalid-str-codec)
************* Module test_api
tests/test_api.py:567:42: W1646: non-text encoding used in str.decode (invalid-str-codec)

-----------------------------------
Your code has been rated at 9.99/10
```

2. I noticed the dashboard is the only component using `six==1.12.0` while the rest use `1.13.0`. Maybe it's not a big deal but I was wondering if it could be quickly updated by running `pip-compile` again?

2020-02-25 04:27 UTC, replaceafill commented on src/dashboard/src/requirements/base.in
> +futures==3.2.0  # used by gunicorn's async workers
Is this line redundant given line 19 below additionally restricts `< 3.0`?

2020-02-25 04:27 UTC, replaceafill commented on src/archivematicaCommon/lib/bindpid.py
> +    import six.moves.configparser as configparser
Looking at how other modules import `configparser` from `six` now, I think we can remove this `ImportError` block.

2020-02-25 04:27 UTC, replaceafill commented on src/dashboard/src/main/migrations/0066_archivesspace_base_url.py
>  except ImportError:
I think we can remove this `ImportError` block now and just depend on the `six` import.

2020-02-25 04:27 UTC, replaceafill commented on src/dashboard/tests/test_api_v2beta.py
> +        ).encode("utf8")
Does this not apply for the new `archivematicaFunctions.b64encode_string` function?

2020-02-25 04:27 UTC, replaceafill commented on src/MCPClient/requirements/base.txt
> +# setuptools==41.0.1        # via opf-fido
I noticed you removed these from the Dashboard requirements in https://github.com/artefactual/archivematica/commit/36e8f9a36ff94395ad7858879a9c09c7a3c7292e. Should we remove these in the client and server as well?

2020-02-25 17:24 UTC, sevein requested changes
This is a lot of work, thank you! I've found some inconsistencies in the way we're doing imports and shared some examples. Can they be fixed this time around? I don't think that's something that we could do mechanically with isort.

2020-02-25 17:24 UTC, sevein commented on src/archivematicaCommon/lib/appconfig.py
> +                six.moves.configparser.NoOptionError,
This feels weird, can we bind the import to `configparser` with `import as`?

2020-02-25 17:24 UTC, sevein commented on src/archivematicaCommon/lib/archivematicaFunctions.py
> +from __future__ import absolute_import
We usually group imports from the same module.

2020-02-25 17:24 UTC, sevein commented on src/archivematicaCommon/lib/appconfig.py
> +import six.moves.configparser
The six import should go to the 3rd-party import group.

2020-02-25 17:24 UTC, sevein commented on src/archivematicaCommon/lib/storageService.py
> +import six.moves.urllib.request
This feels very Javaish! Another exmaple where we could just import `urllib` via local binding.

2020-02-26 00:05 UTC, ross-spencer commented on src/archivematicaCommon/lib/bindpid.py
> +    import six.moves.configparser as configparser
Strange. Wonder what the specific reason for this one was. :man_shrugging:

2020-02-26 00:14 UTC, ross-spencer commented on src/dashboard/tests/test_api_v2beta.py
> +        ).encode("utf8")
I'm not clear on what you mean here @replaceafill, can you elaborate at all?

2020-02-26 00:16 UTC, ross-spencer commented on src/MCPClient/requirements/base.txt
> +# setuptools==41.0.1        # via opf-fido
I think the correct approach is to only modify the `.in` file, so prior to merging I'll run the compile requirements job again, and then I think that will shake this out. What might have happened in that commit was an artifact of the same process.

2020-02-26 00:48 UTC, replaceafill commented on src/dashboard/tests/test_api_v2beta.py
> +        ).encode("utf8")
Yeah. Sorry about not being clear.

I noticed the string resulting from `"{location_uuid}:{relative_path}".format(...)` is then encoded as `utf8`, then encoded as `base64` and finally decoded as `utf8`. That's what the new `archivematicaFunctions.b64encode_string` helper seems to do, right? Unless I'm misinterpreting it in which case consider this noise :blush: 

 So I was thinking something along these lines:

```
path = archivematicaFunctions.b64encode_string(
    "{location_uuid}:{relative_path}".format(
        **{
               "location_uuid": "671643e1-5bec-4a5f-b244-abb76fedb0c4",
               "relative_path": "foo/bar.jpg",
        }
    )
)
```

2020-02-27 07:18 UTC, ross-spencer commented
I've placed this into re-review. AMAUAT look to be passing locally, but have focused mainly on `mo-aip-reingest`, `transfer-policy-check`, `aip-encrypt-mirror` plus `black-box`. I've done some light QA in the user-interface as well.

2020-02-27 07:30 UTC, ross-spencer commented
@replaceafill on `pylint --py3k`. My initial instinct was not to add too much to Helen's PR, but I think it was a good call. I've addressed most of those that I felt were safest for me to do this time around, and we should be better off. There are a few warnings in AM Common I think we can afford to look at with the other components, I think they might affect mcp-client or mcp-server more too. Thank you for the push! 

![image](https://media1.giphy.com/media/LfCt1sR1VweBy/giphy.gif?cid=790b7611234447d245d33fd513fa28853ea8e7c1b760e559&rid=giphy.gif)

2020-02-27 12:29 UTC, replaceafill commented
Thank you for the hard work @ross-spencer! This looks good to me :+1: I'll wait for @sevein to take another look and approve.

2020-02-28 14:29 UTC, sevein approved these changes
Thanks! A few more comments on import style but :+1:.

2020-02-28 14:29 UTC, sevein commented on src/archivematicaCommon/lib/appconfig.py
> +import six.moves.configparser as ConfigParser
Nit: in Py3 it's named `configparser` - action not really required here but it'd be nice.

2020-02-28 14:29 UTC, sevein commented on src/dashboard/src/settings/base.py
> +from six import StringIO
I think that you can remove L29 and that'd be the last import using django.utils.six in the Dashboard!

2020-02-28 14:29 UTC, sevein commented on src/dashboard/src/contrib/mcp/client.py
> +            six.moves.cPickle.dumps(data, protocol=0),
It'd be nice to bind the import to `pickle` since that's the name used in Py3.

2020-02-28 14:29 UTC, sevein commented on src/dashboard/src/components/transfer/views.py
> +        response["message"] = "{}".format(err)
Being a bit pedantic here, if we didn't want to use `format` would the following be more correct?

```suggestion
        response["message"] = six.text_type(err)
```

2020-02-28 14:29 UTC, sevein commented on src/dashboard/src/components/ingest/views.py
> +import six.moves.cPickle
Bind import to `pickle`?

2020-02-28 14:29 UTC, sevein commented on src/dashboard/src/components/helpers.py
> +from six.moves import zip
Group imports.

2020-02-28 14:29 UTC, sevein commented on src/archivematicaCommon/lib/env_configparser.py
> +import six.moves.configparser as ConfigParser
Bind as `configparser`.

2020-02-28 17:38 UTC, ross-spencer commented
Thanks @sevein I've removed the excess import and changed the `"{}".format()` call to `six.text_type` as it looks cleaner. I haven't bound these final imports differently this time. My personal feeling is that changing what the binding is pointing at is nice and easy, it's a reference. Going into the body of the code to change `cPickle` to `pickle` as an example, just at this stage, is just another code-change/copy-replace too much. I'd like to link this issue back to the gearman issue as I think we can think about addressing that as we touch each of those modules again for that work.

2020-03-04 17:19 UTC, merged