Import directory metadata on metadata re-ingest
artefactual/archivematica pull request #1582
Opened 2020-03-06 05:46 UTC by replaceafill

This makes the [`archivematicaCreateMETSReingest.update_metadata_csv`](https://github.com/artefactual/archivematica/blob/e804cc1cc3130c276390b6a0ed63c115c8191576/src/MCPClient/lib/clientScripts/archivematicaCreateMETSReingest.py#L534) function to work with directory entries in the `metadata.csv` file during re-ingest.

Currently the function only checks if the paths in `metadata.csv` match `models.File` instances making it to ignore directory paths. This modifies the function to not fail when a `models.File` can't be found, but instead to look in the `metsrw.METSDocument` for a `metsrw.FSEntry` of type `Directory` that represents the path. A couple of log messages were modified to include the METS lookup.

The new tests seems a bit finicky. I couldn't come up with a cleaner `metsrw.METSDocument` mock and resorted to the logger for verification.

**Note**: be aware that metadata re-ingest breaks with non Dublin Core columns. See https://github.com/archivematica/Issues/issues/1139

Connected to https://github.com/archivematica/Issues/issues/1136

2020-03-06 06:37 UTC, replaceafill commented
@sevein I've marked this ready for review but I noticed Travis is failing and don't understand why. I also get different results when locally I try `make test-mcp-client` or run `tox -e py27` from my `archivematica` directory. Also both of these commands fail for me locally on `qa/1.x` :man_shrugging:

2020-03-07 17:19 UTC, sevein commented
> @sevein I've marked this ready for review but I noticed Travis is failing and don't understand why.

Flaky tests are annoying - I've started another build and it passed. It sounds like we're not doing offline validation and Travis had a connectivity issue - but it should be possible? Possibly related: [[0](https://bugs.launchpad.net/lxml/+bug/1234114)] [[1](https://mailman-mail5.webfaction.com/pipermail/lxml/2018-June/023951.html)].

> I also get different results when locally I try make test-mcp-client or run tox -e py27 from my archivematica directory. Also both of these commands fail for me locally on qa/1.x 🤷‍♂

Do you want to file an issue? What are you seeing?

2020-03-07 18:09 UTC, sevein requested changes
I'm genuinely curious to know why `TestUpdateMetadataCSV` wasn't used in this case?

2020-03-07 18:09 UTC, sevein commented on src/MCPClient/tests/test_archivematicaCreateMETSReingest.py
> +# -*- coding: utf-8 -*-
Why did you choose not to extend `test_reingest.TestUpdateMetadataCSV`?

2020-03-07 18:09 UTC, sevein commented on src/MCPClient/tests/test_archivematicaCreateMETSReingest.py
> +    # Use the logger to verify what happened
> The new tests seems a bit finicky. I couldn't come up with a cleaner metsrw.METSDocument mock and resorted to the logger for verification.

Agree. Perhaps `TestUpdateMetadataCSV` could help here? I'm in favour of testing log statements in some cases though, e.g. it could be important to confirm that an important error is being communicated to the operators.

2020-03-08 22:25 UTC, replaceafill commented
> Do you want to file an issue? What are you seeing?

https://github.com/archivematica/Issues/issues/1140

2020-03-08 22:30 UTC, replaceafill commented on src/MCPClient/tests/test_archivematicaCreateMETSReingest.py
> +# -*- coding: utf-8 -*-
My bad. I keep assuming that the test module names follow the pattern of `test_<client_script_name>` and didn't notice the `archivematicaCreateMETSReingest` is already being tested there. I'll move the new tests :+1:

2020-03-09 13:52 UTC, sevein commented on src/MCPClient/tests/test_reingest_mets.py
> +        dmdsec.findtext(".//dc:description", namespaces=NSMAP) == "A zone for landing"
:+1:

2020-03-09 13:52 UTC, sevein approved these changes
#1136 not yet milestoned but :+1:

2020-03-12 15:19 UTC, merged