Add rights CSV validation, make act not required in CSV workflow
artefactual/archivematica pull request #1733
Opened 2021-05-03 20:27 UTC by bonniegee

Does the following:
* Adds a rights csv endpoint to the validation API (connected to archivematica/issues#563)
* Modifies the rights csv parser so that an act is not required (fixes archivematica/issues#1445)
* Adds or updates associated tests

For the rights csv validation, there were some decisions I made that I wanted to note:
* There were some differences in the language used (e.g., in error messages and variable names) between the Avalon validator and the rights csv parser; for the most part, I used the existing rights csv language
* Though the rights csv parser does not require "basis," I required it in the validator
* Though the rights csv parser does not check that the csv adheres to the PREMIS data dictionary (e.g,. that a copyright rights statement has a copyright status), I checked for this in the validator

2021-05-04 07:11 UTC, sevein reviewed
:exploding_head: this is looking great, @bonniegee. Tests are passing too. I'll take a closer look later today.

Do you have time to update our API docs? There is a [validation section](https://github.com/artefactual/archivematica-docs/blob/1.13/dev-manual/api/api-reference-archivematica.rst#validate) in the new API docs that could use some rewording.

2021-05-04 14:14 UTC, bonniegee commented
Thanks so much, @sevein! I can definitely update the API docs this week.

2021-05-05 11:15 UTC, sevein requested changes
Thank you! Just one minor issue before merging. :+1:

2021-05-05 11:15 UTC, sevein commented on src/dashboard/src/components/api/validators.py
> +                self._check_documentation
I've just realized this is missing the actual function call.

2021-05-05 14:55 UTC, bonniegee commented on src/dashboard/src/components/api/validators.py
> +                self._check_documentation
Thanks for the catch--just fixed!

2021-05-05 15:50 UTC, sevein approved these changes

2021-05-05 16:49 UTC, merged