remove empty bulkextractor logs
artefactual/archivematica pull request #523
Opened 2016-10-31 14:55 UTC by aelkiss

Submitting this PR at the recommendation of @eckardm -- this partially addresses https://github.com/mlibrary/archivematica/issues/2 by drastically cutting down on the number of files that need to be index by removing any empty BulkExtractor logs. The generated `report.xml` still lists any scanners that had no results, so there is still evidence that BulkExtractor ran the scanners.

2016-11-11 01:38 UTC, Hwesta approved these changes
Looks good, thank you!

2016-11-17 22:47 UTC, Hwesta requested changes
Sorry, I took a closer look at this and it has whitespace problems, which are meaningful in Python.  Can you convert all tabs to spaces, and strip trailing whitespace?

2016-11-17 22:47 UTC, Hwesta commented on src/MCPClient/lib/clientScripts/examineContents.py
> +	    filepath = os.path.join(path,filename)
Looks like this should be `filepath = os.path.join(output, filename)` since `path` is undefined.

2016-12-08 14:42 UTC, aelkiss commented
Sorry, I missed this ... fix is pushed now.

2016-12-09 01:05 UTC, Hwesta approved these changes

2016-12-09 01:05 UTC, Hwesta commented
Looks good now, thank you!

2016-12-09 01:10 UTC, Hwesta commented
Committed to qa/1.6.x as 7d02cbf5e449de0d03bf85da1aeb2d10890f746e and qa/1.x as 460ed562a64b7aacbd690a2e62f39b11bfcb092f

2016-12-09 01:10 UTC, closed without merging