clientscripts: change date format in verifyMD5.sh
artefactual/archivematica pull request #629
Opened 2017-06-05 18:44 UTC by scollazo

Problem: Some AIPs can't be saved to samba network shares.

The default date format uses ":", and that's a reserved character for CIFS (samba) mounts, so files named like "logs/checksum.md5-Check-Tue May 16 16:59:21 UTC 2017" can't be stored on them. This affects saving some aips to network filesystems using samba

This commit replaces colons with dots:
 From: Mon Jun  5 14:38:47 EDT 2017
 To:      Mon Jun  5 14.39.17 EDT 2017

2017-06-05 19:41 UTC, sevein commented on src/MCPClient/lib/clientScripts/verifyMD5.sh
> +date_format="%a %b %e %_H.%M.%S %Z %Y"
Should we use instead something like the following?

```bash
date="$(date -u '+%Y%m%dT%H%M%SZ')" # 20170605T194004Z
```

It is compliant with ISO8601 and measured in UTC.

2017-06-05 22:14 UTC, sevein commented on src/MCPClient/lib/clientScripts/verifyMD5.sh
> +date_args="-u +%Y%m%dT%H%M%SZ"  # 20170605T220452Z (UTC ISO8601)
If you want to be consistent with the other variable names, should't be named `dataArgs` instead?

Why don't you run the command here like `checkMD5NoGui` does?

2017-06-06 11:01 UTC, scollazo commented on src/MCPClient/lib/clientScripts/verifyMD5.sh
> +date_args="-u +%Y%m%dT%H%M%SZ"  # 20170605T220452Z (UTC ISO8601)
The `checkMD5NoGui` is executed once, while the `date` command runs each time that a file is verified, I didn't want to change current behavior.

2017-06-06 15:31 UTC, sevein commented on src/MCPClient/lib/clientScripts/verifyMD5.sh
> +date_args="-u +%Y%m%dT%H%M%SZ"  # 20170605T220452Z (UTC ISO8601)
You're right!

2017-06-06 21:59 UTC, nickwilkinson commented
![](https://github.trello.services/images/mini-trello-icon.png) [clientscripts: change date format in verifyMD5.sh](https://trello.com/c/PeujJYmZ/1-clientscripts-change-date-format-in-verifymd5sh)

2017-06-07 00:48 UTC, jhsimpson approved these changes
this is good to merge 👍

2017-06-07 02:44 UTC, sevein requested changes
Nitpick: `date_args` should be `dateArgs`. I believe that consistency matters.

2017-06-08 19:17 UTC, scollazo commented
Changed date_args to keep consistency, and rebased prior to merge

2017-06-08 19:40 UTC, sevein approved these changes

2017-06-09 07:52 UTC, closed without merging

2017-07-27 21:53 UTC, jhsimpson commented
merged in stable/16.x as https://github.com/artefactual/archivematica/commit/ef10d4f532ec7b65ffacf6c8d8068bb3d47ccf75

merged in qa/1.x as https://github.com/artefactual/archivematica/commit/378caf30f6fee62ca3a819d0a2b8427ffc884151