File mod. date update microservice, refs #11063
artefactual/archivematica pull request #635
Opened 2017-06-13 18:37 UTC by mcantelon

Microservices to store file modification dates for later indexing and inclusion in METS file.

2017-06-27 06:12 UTC, sevein requested changes

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +logger = get_script_logger('archivematica.mcp.client.storeFileModificationDates')
You don't need to create a logger if you're not using it.

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +    return datetime.datetime.fromtimestamp(int(mod_time)).strftime('%Y-%m-%d %H:%M:%S')
I think we should use `fromutctimestamp` instead of `fromtimestamp` because we need to recognize that the user's local datetime is likely not UTC but our database is.

It looks like both functions are going to return a naive datetime.datetime which they seem to be perfectly handled by `DateTimeField`, i.e. no need to convert it into a string as that seems to only force Django to [convert it back into a `datetime.datetime`](https://github.com/django/django/blob/d381914aef50e04ca44b9d7bb9274c8351f5b9bf/django/forms/fields.py#L380-L388).

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/archivematicaCreateMETS2.py
> +    etree.SubElement(creatingApplication, ns.premisBNS + "dateCreatedByApplication").text = str(f.modificationtime)[:10]
I would feel more comfortable using a public function like `strftime("%Y-%m-%d")` where the output format is explicit. You're relying on a `__str__` method of `datetime.datetime`, perhaps that's not as reliable?

`f.modificationtime.isoformat()` may also be okay? Date and time combined seem like a good fit here, isn't it?

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/tests/test_store_file_modification.py
> +        finally:
You may want to use `tearDown`(https://docs.python.org/2/library/unittest.html#unittest.TestCase.tearDown) instead.

2017-06-27 06:12 UTC, sevein commented on src/dashboard/src/main/migrations/0033_store_transfer_file_modification_dates.py
> +    MicroServiceChainLinkExitCode.objects.filter(microservicechainlink_id='307edcde-ad10-401c-92c4-652917c993ed').update(nextmicroservicechainlink_id=set_transfer_file_mod_dates_cl_pk)
Nitpick, if you're consistently using 79 columns in this file this is a clear violation of the rule! :P

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +# Copyright 2010-2013 Artefactual Systems Inc. <http://artefactual.com>
2017!

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +# @author Mike Cantelon <mike@artefactual.com>
I think this is so SVN! We really don't need it.

2017-06-27 06:12 UTC, sevein commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +        transfer_file.modificationtime = get_modification_date(shared_directory_path, transfer, transfer_file)
Nitpick, if you passed just a `transfer_file`, then you could access to its transfer with `transfer_file.transfer`?

2017-06-27 06:13 UTC, sevein commented
Small comments but it's looking really good, thanks @mcantelon.

2017-06-28 18:18 UTC, sevein requested changes
Looking good. I've added some comments.

2017-06-28 18:27 UTC, sevein commented on src/MCPClient/tests/test_store_file_modification.py
> +        temp_dir = tempfile.mkdtemp()
You should delete this once you're done with it right?

2017-06-29 22:48 UTC, mcantelon commented on src/MCPClient/lib/clientScripts/storeFileModificationDates.py
> +logger = get_script_logger('archivematica.mcp.client.storeFileModificationDates')
True haha. I've added actual logging now.

2017-07-02 17:54 UTC, sevein commented
@mcantelon, please notice that the CI checks have failed.

2017-07-06 07:59 UTC, sevein approved these changes
Tested, it works great.

2017-07-06 08:00 UTC, merged