[WIP] Config cleanup
artefactual/archivematica pull request #670
Opened 2017-07-07 17:00 UTC by helenst

**_This is a merge of work from the JiscRDSS fork (see #664) - it's WIP as I'm still trying to get it to deploy successfully with Ansible._**

MCPServer, MCPClient and Dashboard have been changed in this commit with the
following goals:

- Stop sharing configuration between components.
- Use django.conf to manages config.
- Manage config defaults within code.
- Look up environment variables:
  - ARCHIVEMATICA_DASHBOARD_*
  - ARCHIVEMATICA_MCPSERVER_*
  - ARCHIVEMATICA_MCPCLIENT_*

dbsettings, clientConfig.conf or serverConfig.conf are still considered if they
exist - they will be merged with the default INI in code. Environment strings
are applied last.

Client scripts are now executed using MCPClient's `settings.common`. So now
when they look up `django.conf` they're not looking at the Dashboard config.
It wasn't correct to assume that its config was available.

2017-07-12 16:55 UTC, helenst commented
This now successfully runs a transfer so I'm de-WIPing it for review.

2017-07-12 18:29 UTC, sevein commented
@helenst, great job! I'm having a meeting with @jrwdunham today to introduce him to these changes. I'm hoping we can get this merged very soon! Thank you!

2017-07-17 22:39 UTC, jrwdunham requested changes
I reviewed the changes and ran the core AM acceptance tests on a VM deployed with these changes (and deployed via https://github.com/artefactual-labs/ansible-archivematica-src/pull/115) and they passed.

After rebasing this on current qa/1.x, I believe you will have to add a call to
``setup_dicts(mcpclient_settings)`` in the new policyCheck.py client script.

I also am wondering why the kioskMode var was removed.

After that, I think this is good to merge.

2017-07-17 22:39 UTC, jrwdunham commented on src/dashboard/src/components/accounts/views.py
> -
Why was the `kioskMode` config param removed?

2017-07-17 22:52 UTC, sevein commented on src/dashboard/src/components/accounts/views.py
> -
Undocumented and unused. I think this was used at some point when we didn't have non-super users.

2017-07-17 23:10 UTC, jrwdunham commented
Also, these changes cause 3 of the tests to fail in archivematicaCommon/tests/test_dicts.py. I think that should be fixed.

2017-07-17 23:10 UTC, jrwdunham commented on src/dashboard/src/components/accounts/views.py
> -
Ok. Thanks sevein.

2017-07-19 16:41 UTC, helenst commented
@jrwdunham Thanks! I've fixed those tests so that they work now.

2017-07-19 17:18 UTC, sevein approved these changes

2017-07-19 17:20 UTC, jrwdunham commented
@helenst Thanks! Now, unless I'm wrong, I think you just need to rebase and add the `setup_dicts` call in the new client script policyCheck.py.

2017-07-19 18:45 UTC, helenst commented
@jrwdunham It's all rebased now and I've updated the policycheck script.

2017-07-19 18:58 UTC, jrwdunham approved these changes

2017-07-19 22:45 UTC, merged