Fix deps mismatch between AM and AT, refs #11363
artefactual/archivematica pull request #678
Opened 2017-07-16 01:35 UTC by jraddaoui

- Upgrade jQuery UI to v1.12.1 to match the version used in the AT
- Avoid importing jQuery twice in some templates (and other JS files)
- Update Appraisal tab webpack file

2017-07-16 01:36 UTC, jraddaoui commented
https://github.com/artefactual-labs/appraisal-tab/pull/159

2017-07-17 18:50 UTC, sevein commented
@jraddaoui, I'm wondering if we should repurpose this PR in order to move the sources of the appraisal tab and the transfer browser to this repo. What do you think?
I understand that it may require a significant effort but it'll pay off soon. The appraisal-tab and transfer_browser repos served well when we wanted to work on them in parallel but that's not the case anymore.

```
src/dashboard/
├── debian/
├── install/
├── osdeps/
├── src/
│   ├── media/build/appraisal-tab.js
│   ├── media/build/appraisal-tab.css
│   ├── media/build/transfer-browser.js
│   └── media/build/transfer-browser.css
├── tests/
├── .eslint.rc
├── webpack.config.js
└── package.json
```

I think that `src/media/build` can be gitignored for now - we may opt to track them in git if slows down deployments significantly or if it makes packaging too painful. It's also ok not to fix all the things now (e.g. including old assets is ok, stick with webpack and npm probably best, etc...) - we can focus on get it working, figure out the dev/deploy workflow changes, update our Ansible role and dev documentation.

Thoughts?

2017-07-17 18:54 UTC, sevein commented
Another benefit would be to stop serving the old `/media/js/transfer_browser.js` (2.6 MB) and `/media/js/appraisal_tab.js` (4.8 MB) in addition to all the extra assets that belong to the Dashboard.

2017-07-17 19:45 UTC, sevein requested changes
Please see my comments above.

2017-07-20 12:13 UTC, jraddaoui commented
I think that's a great idea. I'll ask for time ;)

2017-07-26 19:53 UTC, sevein commented on src/dashboard/frontend/appraisal-tab/package.json
> +  "description": "Appraisal tab prototype for Archivematica",
Excepting it's not a prototype anymore! :D

2017-07-26 19:54 UTC, jraddaoui commented
Hi Sevein,

As we talked in the chat, I'll leave you the changes required in the Ansible role. I was using qa/1.7.x for the archivematica-src role with this branch and, when the Vagrant box was ready, all I had to do was:

`vagrant ssh
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs build-essential
cd /vagrant/src/archivematica/src/dashboard/frontend/appraisal-tab
npm install
cd /vagrant/src/archivematica/src/dashboard/frontend/transfer-browser
npm install`

Please, le me know if you need more info or if you find anything to change in here.

Thanks!

2017-07-31 20:34 UTC, sevein commented
Thanks, Radda! I'll update the Ansible role when I have a chance!

2017-08-11 23:28 UTC, sevein commented
I've rebased!

2017-08-12 02:09 UTC, sevein approved these changes
I just got this to work with https://github.com/artefactual-labs/ansible-archivematica-src/pull/128. Thanks, @jraddaoui - it's working great!

2017-08-12 02:10 UTC, sevein commented
Forgot to mention that I had to add 8543f51 because WhiteNoise won't accept that stylesheet as it was confusing the content of that comment with a real url link which couldn't find because it was URL-encoded. Very confusing, that took me a while!

2017-09-01 13:14 UTC, sevein commented
Rebased.

2017-09-05 11:22 UTC, jraddaoui commented
Rebased

2017-09-05 13:00 UTC, jraddaoui commented
Tested it alongside https://github.com/artefactual-labs/ansible-archivematica-src/pull/128 and it seems to be working as expected. I'm not sure what's the best place to put the 'node_modules' workaround for Vagrant users but, since this is blocking three issues now, I'll merge both PRs and we'll figure out later.

Thanks @sevein!

2017-09-05 13:05 UTC, jraddaoui commented
Merged in https://github.com/artefactual/archivematica/commit/40aa9d90ce1e50d7dce080e5fef4fdb374ae42d9

2017-09-05 13:05 UTC, closed without merging