Handle null values in ingested json metadata
artefactual/archivematica pull request #716
Opened 2017-08-16 20:50 UTC by thatandromeda

Resolves #709.

(I also owe you a contributor agreement, which I need to clear with work, though I don't anticipate any problems.)

2017-08-18 18:25 UTC, jraddaoui requested changes
Thank you @thatandromeda, this is looking great!

See my comments bellow.

2017-08-18 18:25 UTC, jraddaoui commented on src/MCPClient/lib/clientScripts/jsonMetadataToCSV.py
>          return [i.encode('utf-8') for i in item]
I think we should handle the same case inside this `for` loop, for `null` values inside lists. For example:

```
[
  {
    "dc.identifier": "foo",
    "filename": "objects/foo.jpg",
    "dc.subject": [
      "bar",
      null
    ]
  }
]
```

2017-08-18 18:25 UTC, jraddaoui commented on src/MCPClient/tests/test_json_conversion.py
> +
If you could update or add a new test case with a `null` value inside a list, that would be great.

2017-08-18 18:51 UTC, thatandromeda commented
OK, I've added the changes, and I've also emailed my CLA to agreement@artefactual.

2017-08-18 18:53 UTC, sevein commented
Do any of you know if there is a reason why these tests are using `subprocess`? It seems very inefficient right?

2017-08-18 18:55 UTC, thatandromeda commented
I don't - I was copy/pasting existing tests.

2017-08-18 18:56 UTC, sevein commented
@thatandromeda hey did you target the stable/1.6.x because you're hoping your fix to be included in AM 1.6.1? Generally we target `qa/1.x`, for the next minor release.

@jhsimpson thoughts?

2017-08-18 19:24 UTC, thatandromeda commented
I used whatever default Github handed me. Using Github to rebase this looks messy but I can try to rebase it locally - you want me to have started on, and be planning to merge into, `qa/1.x`?

2017-08-18 19:31 UTC, sevein commented
I'm hoping @jhsimpson can make that call. I've heard he's thinking on a AM 1.6.1 release but I haven't really been in the loop. Merging into 1.6 and cherry-picking (we can do that) would be ok to me too.

Thank you!

2017-08-19 09:43 UTC, jraddaoui commented
Thank you @thatandromeda, I'll give it a try today before merging.

@sevein, I chatted about this yesterday with @jhsimpson and this should go to stable/1.6.x too, so we could merge in here and cherry-pick to qa/1.x. However, I'm wondering what should be the best way to do it, should I ask @thatandromeda to squash the three commits? I think it will change the author if I do it myself. Or should I merge (--ff-only) the three commits directly? Thanks!

2017-08-21 15:14 UTC, thatandromeda commented
Awaiting your preferences on git history - whatever you want is fine.

2017-08-21 16:46 UTC, jraddaoui commented
Thanks @thatandromeda! Just tested it and works as expected.

If you could squash the last two commits in one and make sure your stable/1.6.x branch is up-to-date with this one, that would be perfect ;)

2017-08-22 17:21 UTC, merged

2017-08-22 17:26 UTC, jraddaoui commented
Thank you again @thatandromeda!

I've added https://github.com/artefactual/archivematica/commit/4f66cf004fbc7a27d572ac2e73350d56461ea0b7 to qa/1.x too ;)