Make METS normative structMap creation optional.
artefactual/archivematica pull request #833
Opened 2017-12-10 08:05 UTC by mcantelon

Add a chain choice link that allows the user to select whether
or not they want a normative structMap created when METS is
generated. Normative structMaps in METS break DIP upload
compatibility with AtoM 2.4.0.

2017-12-13 18:11 UTC, mcantelon commented
Oops. Just noticed this failed checks. I'll fix.

2017-12-14 22:36 UTC, jrwdunham requested changes
Overall, this looks good. I have confirmed that it works both with a
pre-configured choice and by making the choice in the GUI.

I have noticed that if you create an AIP that DOES document empty dirs and then
set the config to NOT document empty dirs and then re-ingest the AIP you will
still get the normative structMap in your METS. I don't know if this is an
issue, but I'm just pointing it out here.

Once the user-facing choice text is changed to "Document empty directories" and
the unit tests are made to pass, I think this can be merged.

2017-12-14 22:36 UTC, jrwdunham commented on src/dashboard/src/components/administration/forms.py
> +        'label': _('Add normative structMap to METS XML'),
Can you change this so that it is something that will make more sense to an end user? I think it should be `'Document empty directories'` (cf. https://github.com/artefactual/archivematica/issues/822#issuecomment-349145732) because the purpose of the normative logical structMap is to allow AM to document empty directories.

2017-12-14 22:36 UTC, jrwdunham commented on src/MCPServer/lib/archivematicaMCP.py
> +    <!-- Add normative structMap to METS XML: Yes -->
Was it agreed that "Yes" should be the default here? I'm not disagreeing with this default, I'm just double-checking.

2017-12-15 00:15 UTC, mcantelon commented on src/MCPServer/lib/archivematicaMCP.py
> +    <!-- Add normative structMap to METS XML: Yes -->
I'm not sure if we decided on this. I'll ask on chat.

2017-12-15 00:15 UTC, mcantelon commented on src/dashboard/src/components/administration/forms.py
> +        'label': _('Add normative structMap to METS XML'),
Sounds good.

2017-12-15 21:07 UTC, jhsimpson commented on src/MCPServer/lib/archivematicaMCP.py
> +    <!-- Add normative structMap to METS XML: Yes -->
default of Yes is good

2017-12-15 21:24 UTC, mcantelon commented
@jrwdunham Okay this is ready for a final review, but now it's showing it has conflicts. I think I did the dev against qa/1.x, maybe I should have against stable/1.7.

2017-12-20 18:52 UTC, mcantelon commented
@jrwdunham I've added some logic to archivematicaCreateMETSReingest.py to delete any existing normative structmaps before a new one is created. If you could test to see if it fixes the issue you ran into, that'd be awesome (I'm having trouble getting reingest to work on my AM dev VM).

2017-12-22 22:20 UTC, jrwdunham requested changes
I think the changes to archivematicaCreateMETSReingest.py will work but I think the METS update should only remove normative structmaps if the `createNormativeStructmap` option is `False`.

2017-12-22 22:20 UTC, jrwdunham commented on src/MCPClient/lib/clientScripts/archivematicaCreateMETSReingest.py
> +
@mcantelon this approach looks better/simpler than modifying metsrw, but doesn't this need to be contingent on `createNormativeStructmap`? I mean, I think the `update_mets` function needs a kwarg like `keep_normative_structmap=True` which you set to `False` when `createNormativeStructmap` is `False` in archivematicaCreateMETS2.py.

2017-12-31 01:12 UTC, mcantelon commented
@jrwdunham Makes sense... I've updated this branch to make the removal of normative structmaps conditional.

2018-01-04 23:44 UTC, jrwdunham commented
I rebased this against the current stable/1.7.x, bumped the migration and made a fix to the "keep normative structmap" logic. My testing has confirmed that you can now create an AIP whose METS file has a normative logical structMap, fully reingest that AIP and choose not to document empty directories (in which case the normative structMap is removed from the revised METS), and then again fully reingest that AIP and choose to again document empty dirs (in which case the normative structMap is restored).

I think this can be merged now.

2018-01-04 23:44 UTC, jrwdunham commented
👍

2018-01-04 23:44 UTC, jrwdunham approved these changes

2018-01-05 00:10 UTC, merged

2018-01-05 00:42 UTC, jrwdunham commented
Cherry-picked to qa/1.x as 642c3fbc29b82401267dcfc5599af0b5cf08e33d, df18fe78426ef52564f7f4b370fa4b39c9713c3f, and 2c47d3736fc5d5bef13c37017010af10d9aa89d5.