Dashboard: add rebuild-transfer-backlog
artefactual/archivematica pull request #894
Opened 2018-01-23 23:29 UTC by sevein

rebuild-transfer-backlog used to belong to archivematica-devtools. This
pull request implements it as a Dashboard management command for the
following reasons:

- Its implementation does not make use of formal APIs.
- It was designed to run in the environment where Archivematica was installed.
- The command MUST be used during AM upgrades, i.e.: devtools is for devs.

The installation docs will need to be upgraded accordingly.

In am.git, you can run the command as follows:

    $ docker-compose run \
          --no-deps --rm \
          --entrypoint /src/dashboard/src/manage.py \
              archivematica-dashboard \
                  rebuild_transfer_backlog --no-prompt

It fixes https://github.com/artefactual/archivematica-devtools/issues/52.

2018-01-24 00:23 UTC, jhsimpson commented
The name of this PR doesn't really reflect the full scope of the change, I don't think.  This PR refactors the sanitize names client script, in addition to adding a new management command.

Is there some risk that this is altering the behaviour of the 'Clean Up Names' microservice group?  What do you think about splitting this PR into two (one to alter sanitize names, one to add the management command) or else rename this PR to reflect the scope of the suggested change?

2018-01-24 00:49 UTC, sevein commented
That was not a change introduced arbitrarily, I just moved the sanitization functions to a new module in archivematicaCommon so they can be used by rebuild-transfer-backlog. Otherwise we would need to install the MCPClient sources into the Dashboard environment.

2018-01-24 21:37 UTC, sevein commented
@jhsimpson I've removed the use of the sanitize function.

2018-01-26 23:50 UTC, jrwdunham requested changes
I have confirmed this works as advertised. I have a few requests for minor changes and a question.

2018-01-26 23:50 UTC, jrwdunham commented on src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py
> +        """Request tranfer reindex in Storage Service."""
typo "tranfer".

2018-01-26 23:50 UTC, jrwdunham commented on src/dashboard/src/main/management/commands/__init__.py
> +    return result[0].lower() == "y"
Kinda weird that I could enter "yno" here and this would be interpreted as "yes".

2018-01-26 23:50 UTC, jrwdunham commented on src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py
> +        mets_bns = '{http://www.loc.gov/METS/}'
Maybe this should be taken from archivematicaCommon/lib/namespaces.py so it is centralized. Same with xlink.

2018-01-26 23:50 UTC, jrwdunham commented on src/dashboard/src/main/management/commands/rebuild_transfer_backlog.py
> +                    currentlocation=location_with_token,
Given @jhsimpson's [comment](https://github.com/artefactual/archivematica/pull/894#issuecomment-359978178), I'm wondering if what you were doing here previously was getting the original (unsanitized) file name/path from the METS file. In any case, shouldn't we be doing that? I mean, given how this works right now, if I backlog a transfer containing files with sanitizable names, then delete File rows and rebuild the index using this command, then won't the `originallocation` value be technically incorrect. Probably a minor issue, but just pointing it out

2018-01-30 16:52 UTC, jhsimpson approved these changes
the refactoring looks good to me.  Other than responding to @jrwdunham comments, this looks good to me now.

2018-01-30 21:49 UTC, sevein commented
@jrwdunham please take another look. 97911e0 addresses the issues you mentioned.

2018-01-31 18:51 UTC, jrwdunham commented
Hey @sevein. Yes, 97911e056e509beb6acc18f18416059d402dca44 addresses most of the issues. However, I'm still tripping up on the sanitization part. I created a transfer from a directory that contains both a directory and a file whose names will be sanitized, specifically it looked like sanitizeme/bi!son/buf!falo.txt. I put this transfer in backlog. Then I manually deleted everything in the Files table:

    mysql> SET foreign_key_checks = 0;
    mysql> delete from Files;
    mysql> SET foreign_key_checks = 1;

Then I ran your `rebuild_transfer_backlog` command and got this (line 159):

    File not found: /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/wed1-1eb01134-5476-4602-88ed-bcf6d3fa1f67/objects/bi!son/buf!falo.txt

It seems to me that you need to sanitize all the elements of the path in addition to just the basename. Also, you need to do it earlier on because the file/path on disk is sanitized:

    $ docker-compose exec archivematica-storage-service ls /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/wed1-1eb01134-5476-4602-88ed-bcf6d3fa1f67/objects/
bi_son
    $ docker-compose exec archivematica-storage-service ls /var/archivematica/sharedDirectory/www/AIPsStore/transferBacklog/originals/wed1-1eb01134-5476-4602-88ed-bcf6d3fa1f67/objects/bi_son
buf_falo.txt

Also, when you call `File.objects.create` I think you need to give `originallocation` the unsanitized path and `currentlocation` the sanitized path.

My larger concern is that I wonder what's the point of just reconstructing the File table. As shown above, I had remove MySQL's foreign key checks in order to simulate the state of affairs where that table would need to be re-created. This seems highly artificial. If it did need to be re-created, then presumably the Events and Agents tables would also need fixing. This seems like a rabbithole. Maybe reconstructing the Files table is not worth the effort...

2018-02-06 19:30 UTC, merged

2018-02-06 19:30 UTC, sevein commented
951f5efe in stable/1.7.x