Change 'None' to '' in default AtoM config
artefactual/archivematica pull request #896
Opened 2018-01-24 00:20 UTC by jrwdunham

Fixes migration 0032 so that when an AtoM setting has no value in the previous state of the database it will be set to the empty string instead of `str(None)`, i.e., 'None'.

Fixes #879.

2018-01-24 00:34 UTC, sevein requested changes
Could you make a new migration instead? 0032 is already used in production in the JiscRDSS fork.

2018-01-25 02:40 UTC, jrwdunham commented
@sevein I went ahead and made this into a migration. Any objections to merging?

2018-01-25 17:18 UTC, sevein approved these changes

2018-01-25 19:09 UTC, merged

2018-01-25 19:11 UTC, jrwdunham commented
Cherry-picked to stable/1.7.x as a9e836d62e19e8d3e65a8077334e01c97b377b09.