MCPClient: osdeps, delete python-unidecode
artefactual/archivematica pull request #915
Opened 2018-02-06 19:38 UTC by sevein

Installed via pip.

This closes #897.

2018-02-07 21:22 UTC, scollazo commented
The package should also be removed from https://github.com/artefactual-labs/am-packbuild/blob/master/rpm/archivematica/archivematica.spec#L53

2018-02-07 23:39 UTC, scollazo requested changes
There is another place where this change needs to be made

2018-02-08 00:13 UTC, sevein commented
> There is another place where this change needs to be made

And how does that block this PR?

2018-02-08 00:38 UTC, scollazo approved these changes

2018-02-08 00:48 UTC, merged