CHANGELOG: add link to release notes
artefactual/archivematica pull request #985
Opened 2018-03-13 15:37 UTC by sevein

CC @cdekok

2018-03-15 01:20 UTC, ross-spencer requested changes
Hi @sevein I think a header of some sort would be nice. The line break mechanism can follow the pattern established in the document:

Suggestion:
```
Archivematica 1.6.0 onwards
=====

This CHANGELOG is not longer maintained. Please visit the Archivematica wiki for comprehensive [release notes](https://wiki.archivematica.org/Release_Notes).
```

2018-03-15 17:08 UTC, sevein commented
Thanks @ross-spencer, please take a look again.

2018-03-15 20:10 UTC, ross-spencer approved these changes

2018-03-15 20:20 UTC, merged

2018-03-16 18:17 UTC, sevein commented
Apparently somehow I cherry picked the commit before the review. Fixed now.

ad40b39440ef644a673b2ecb7802d8c9a2a1822e and 790cddabf0281995a59c49437fe9b8d22f02a565 in `stable/1.7.x`
c302ff34cdf855a37c6bfc1e301f695c2681591d and 22cbdffac6f9784957306baeaa0e326f6e611cf4 in `qa/1.x`